"""Defines local PyPI-based repositories. Their deps
should be installed later in WORKSPACE file to be accessible.
`pip_parse` takes a `requirements_lock` file as input, which is
generated by the `bazel run :requirements.update` command."""

load("@com_github_reboot_dev_pyprotoc_plugin//bazel:pypi_repos.bzl", pyprotoc_plugin_pypi_repos = "pypi_repos")

def pypi_repos():
    pyprotoc_plugin_pypi_repos()
