"""Adds repositories/archives."""

########################################################################
# DO NOT EDIT THIS FILE unless you are inside the
# https://github.com/3rdparty/bazel-rules-jemalloc repository. If you
# encounter it anywhere else it is because it has been copied there in
# order to simplify adding transitive dependencies. If you want a
# different version of bazel-rules-jemalloc follow the Bazel build
# instructions at https://github.com/3rdparty/bazel-rules-jemalloc.
########################################################################

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

def repos(external = True, repo_mapping = {}):
    maybe(
        http_archive,
        name = "rules_foreign_cc",
        url = "https://github.com/bazelbuild/rules_foreign_cc/archive/0.5.1.tar.gz",
        sha256 = "33a5690733c5cc2ede39cb62ebf89e751f2448e27f20c8b2fbbc7d136b166804",
        strip_prefix = "rules_foreign_cc-0.5.1",
        repo_mapping = repo_mapping,
    )

    # if "rules_foreign_cc" not in native.existing_rules():
    #     http_archive(
    #         name = "rules_foreign_cc",
    #         url = "https://github.com/bazelbuild/rules_foreign_cc/archive/0.5.1.tar.gz",
    #         sha256 = "33a5690733c5cc2ede39cb62ebf89e751f2448e27f20c8b2fbbc7d136b166804",
    #         strip_prefix = "rules_foreign_cc-0.5.1",
    #         repo_mapping = repo_mapping,
    #     )

    maybe(
        http_archive,
        name = "com_github_3rdparty_bazel_rules_jemalloc",
        url = "https://github.com/3rdparty/bazel-rules-jemalloc/archive/5.2.1.tar.gz",
        sha256 = "ed51b0b37098af4ca6ed31c22324635263f8ad6471889e0592a9c0dba9136aea",
        strip_prefix = "bazel-rules-jemalloc-jemalloc-5.2.1",
        repo_mapping = repo_mapping,
    )

    # if external and "com_github_3rdparty_bazel_rules_jemalloc" not in native.existing_rules():
    #     http_archive(
    #         name = "com_github_3rdparty_bazel_rules_jemalloc",
    #         url = "https://github.com/3rdparty/bazel-rules-jemalloc/archive/5.2.1.tar.gz",
    #         sha256 = "ed51b0b37098af4ca6ed31c22324635263f8ad6471889e0592a9c0dba9136aea",
    #         strip_prefix = "bazel-rules-jemalloc-jemalloc-5.2.1",
    #         repo_mapping = repo_mapping,
    #     )
