#!/bin/sh

# Check for existence of git.
which git >/dev/null
if [[ $? != 0 ]]; then
  printf "Failed to find 'git' (please install or update your path)\n"
  exit 1
fi

# Get top-level directory so we can look for tools/pre-commit file.
directory=$(git rev-parse --show-toplevel)

if [[ ! -f "${directory}/tools/pre-commit" ]]; then
  printf "Failed to find 'tools/pre-commit'"
  exit 1
fi

ln -s -f ../../tools/pre-commit "${directory}/.git/hooks/pre-commit"

