version: 1.0.0
merge_rules:
  labels:
    trigger: mergequeue-ready
    skip_line: ""
    merge_failed: mergequeue-failed
    skip_delete_branch: ""
  update_latest: true
  delete_branch: true
  use_rebase: true
  enable_comments: true
  ci_timeout_mins: 0
  preconditions:
    number_of_approvals: 1
    required_checks:
      - check_code_style (ubuntu-latest)
      - Build and Test (ubuntu-latest, 64_core_GitHub_hosted, sudo, --config=asan --test_env=ASAN_OPTIONS=detect_odr_violation=0)
      - Build and Test (macos-latest, macos-latest, sudo, bazelisk)
    use_github_mergeability: false
    conversation_resolution_required: true
  merge_mode:
    type: default
    parallel_mode: null
  auto_update:
    enabled: false
    label: ""
    max_runs_for_update: 0
  merge_commit:
    use_title_and_body: false
  merge_strategy:
    name: squash
    override_labels:
      squash: mergequeue-squash
      merge: ""
      rebase: mergequeue-rebase
