name: Build and Run All Tests

# We use action's triggers 'push' and 'pull_request'.
# The strategy is the following: this action will be
# triggered on any push to 'main' branch and any pull
# request to any branch. Thus we avoid duplicate work-
# flows.
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:
    inputs:
      # Live debug failures using tmate by toggling input parameter
      # 'debug_enabled':
      # https://github.com/mxschmitt/action-tmate#manually-triggered-debug
      # When manually running this workflow:
      # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            sudo-command: "sudo"
            # Explicitly not using `dazel` here as we don't want to
            # build/test on Linux but on macOS!
            bazel-command: "bazelisk"
            bazel-config: ""
            output-user_root: ""
          - os: ubuntu-latest
            sudo-command: "sudo"
            bazel-command: "dazel"
            bazel-config: "--config=asan"
            output-user_root: ""
          - os: windows-2019
            sudo-command: "" # The Windows runner already runs as root.
            # Explicitly not using `dazel` here as we don't want to
            # build/test on Linux but on Windows!
            bazel-command: "bazelisk"
            bazel-config: ""
            # Fixes issue #248.
            output-user_root: "--output_user_root=C:/bzl"
      # Don't fail all workflows if one fails as we're still getting
      # to a stable build right now and when one fails it doesn't mean
      # they all will fail.
      fail-fast: false

    defaults:
      run:
        shell: bash

    env:
      GOOGLE_APPLICATION_CREDENTIALS: service_account_credentials.json
      GOOGLE_REMOTE_CACHE: https://storage.googleapis.com/reboot-dev-eventuals-remote-cache

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Set up remote cache credentials
        # With the exception of GITHUB_TOKEN, secrets are not passed to the runner
        # when a workflow is triggered from a forked repository.
        if: github.event.pull_request.head.repo.full_name == '3rdparty/eventuals'
        uses: jsdaniell/create-json@1.1.2
        with:
          name: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
          json: ${{ secrets.GCP_GITHUB_INFRA_REMOTE_CACHE_CREDENTIALS }}

      # Install 'wheel' for Python on Windows as required for running
      # commands like 'python setup.py bdist_wheel'.
      - name: Install Python 'wheel'
        if: ${{ matrix.os == 'windows-2019' }}
        run: ${{ matrix.sudo-command }} pip3 install wheel

      # Install Dazel for use on Linux so that we use the same build
      # tooling in our Actions as we do on our workstations.
      - name: Install Dazel
        if: ${{ matrix.bazel-command == 'dazel' }}
        run: ${{ matrix.sudo-command }} pip3 install dazel

      # Invoke 'dazel version' in order to build the Docker container
      # as a separate step so we can track how long it takes and
      # optimize as necessary.
      - name: Dazel Docker Build
        if: ${{ matrix.bazel-command == 'dazel' }}
        run: dazel version

      # With the exception of GITHUB_TOKEN, secrets are not passed to the runner
      # when a workflow is triggered from a forked repository, and thus we
      # can only set up a remote cache if this pull request comes from a
      # non-forked repository.
      - name: Set Up Remote Cache
        if: github.event.pull_request.head.repo.full_name == '3rdparty/eventuals'
        run: |
         echo "BAZEL_REMOTE_CACHE=--remote_cache=${{ env.GOOGLE_REMOTE_CACHE }} \
           --google_credentials=${{ env.GOOGLE_APPLICATION_CREDENTIALS }}" \
           >> $GITHUB_ENV

      - name: Build
        run: |
          ${{ matrix.bazel-command }} \
            ${{ matrix.output-user_root }} \
            build \
            ${{ matrix.bazel-config }} \
            ${{ env.BAZEL_REMOTE_CACHE }} \
            --verbose_failures \
            --spawn_strategy=local \
            -c dbg \
            --strip="never" \
            ...

      - name: Test
        run: |
          ${{ matrix.bazel-command }} \
            ${{ matrix.output-user_root }} \
            test \
            ${{ matrix.bazel-config }} \
            --experimental_ui_max_stdouterr_bytes=-1 \
            ${{ env.BAZEL_REMOTE_CACHE }} \
            --verbose_failures \
            --spawn_strategy=local \
            -c dbg \
            --strip="never" \
            --test_output=errors \
            test/... \
            --test_arg=--gtest_shuffle \
            --test_arg=--gtest_repeat=100

      - name: Debug using tmate (if failure)
        uses: mxschmitt/action-tmate@v3
        # Optionally enable tmate debugging if the workflow was manually-triggered
        # with `debug_enabled` set to `true`.
        # https://github.com/mxschmitt/action-tmate#manually-triggered-debug
        if: ${{ failure() && github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
