name: Build and Run All Tests

# We use action's triggers 'push' and 'pull_request'.
# The strategy is the following: this action will be
# triggered on any push to 'main' branch and any pull
# request to any branch. Thus we avoid duplicate work-
# flows.
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      # Live debug failures using tmate by toggling input parameter
      # 'debug_enabled':
      # https://github.com/mxschmitt/action-tmate#manually-triggered-debug
      # When manually running this workflow:
      # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
      debug_enabled:
        description: "Enable tmate debugging"
        type: boolean
        default: false

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: macos-latest
            sudo-command: "sudo"
            bazel-config: ""
            output-user_root: ""
          - runner: 64_core_GitHub_hosted
            sudo-command: "sudo"
            bazel-config: "--config=asan --test_env=ASAN_OPTIONS=detect_odr_violation=0"
            output-user_root: ""
          - runner: windows-2019
            sudo-command: "" # The Windows runner already runs as root.
            bazel-config: ""
            # Fixes issue #248.
            output-user_root: "--output_user_root=C:/bzl"
      # Don't fail all workflows if one fails as we're still getting
      # to a stable build right now and when one fails it doesn't mean
      # they all will fail.
      fail-fast: false

    defaults:
      run:
        shell: bash

    env:
      GOOGLE_APPLICATION_CREDENTIALS: service_account_credentials.json

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Report version of `clang`
        run: |
          clang --version

      - name: Set up Read+Write remote cache credentials
        # With the exception of GITHUB_TOKEN, secrets are not passed to the runner
        # when a workflow is triggered from a forked repository.
        if: github.ref == 'refs/heads/main'
        uses: jsdaniell/create-json@1.1.2
        with:
          name: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
          json: ${{ secrets.GCP_GITHUB_INFRA_REMOTE_CACHE_CREDENTIALS }}

      # Install 'wheel' for Python on Windows as required for running
      # commands like 'python setup.py bdist_wheel'.
      - name: Install Python 'wheel'
        if: ${{ matrix.os == 'windows-2019' }}
        run: ${{ matrix.sudo-command }} pip3 install wheel

      # With the exception of GITHUB_TOKEN, secrets are not passed to the runner
      # when a workflow is triggered from a forked repository, and thus we
      # can only set up a remote cache if this pull request comes from a
      # non-forked repository.
      - name: Set up Read+Write Remote Cache
        if: github.ref == 'refs/heads/main'
        run: |
          echo "BAZEL_REMOTE_CACHE=--remote_upload_local_results=true \
            --google_credentials=${{ env.GOOGLE_APPLICATION_CREDENTIALS }}" \
            >> $GITHUB_ENV

      - name: Build
        run: |
          bazelisk \
            ${{ matrix.output-user_root }} \
            build \
            ${{ matrix.bazel-config }} \
            ${{ env.BAZEL_REMOTE_CACHE }} \
            --verbose_failures \
            -c dbg \
            --strip="never" \
            ...

      - name: Test
        run: |
          bazelisk \
            ${{ matrix.output-user_root }} \
            test \
            ${{ matrix.bazel-config }} \
            --experimental_ui_max_stdouterr_bytes=-1 \
            ${{ env.BAZEL_REMOTE_CACHE }} \
            --verbose_failures \
            -c dbg \
            --strip="never" \
            --test_output=errors \
            test/... \
            --test_arg=--gtest_shuffle \
            --test_arg=--gtest_repeat=100

      - name: Debug using tmate (if failure)
        uses: mxschmitt/action-tmate@v3
        # Optionally enable tmate debugging if the workflow was manually-triggered
        # with `debug_enabled` set to `true`.
        # https://github.com/mxschmitt/action-tmate#manually-triggered-debug
        if: ${{ failure() && github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
