name: C/C++ Style Check

on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run bootstrap
      run: cd tools/ && ./bootstrap
    - name: Install prototool
      run: brew install prototool  
    - name: Check all .proto files on correct code format
      run: chmod +x tools/check_style_proto && tools/./check_style_proto  
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v4.0.0
      with:
        clang-format-version: '12'
        check-path: '.'
