name: Check Code Style

# We use action's triggers 'push' and 'pull_request'.
# The strategy is the following: this action will be
# triggered on any push to 'main' branch and any pull
# request to any branch. Thus we avoid duplicate work-
# flows.
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  # Optionally use tmate to live debug failures:
  # https://github.com/mxschmitt/action-tmate#manually-triggered-debug
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  check_code_style:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]

    steps:
      # We should checkout the repo with submodules
      # cause we need to have symlink to
      # dev-tools/.clang-format file for all code
      # style checks.
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # Call the composite action to check files
      # for correct code style. This action (action.yml)
      # is in `dev-tools` submodule.
      - uses: ./submodules/dev-tools/check-code-style
        with:
          os: ${{matrix.os}}

      - name: Debug using tmate (if failure)
        uses: mxschmitt/action-tmate@v3
        # Optionally enable tmate debugging of manually-triggered workflows.
        # https://github.com/mxschmitt/action-tmate#manually-triggered-debug
        if: ${{ failure() && github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
