name: C/C++ Style Check

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "master"
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run bootstrap
      run: cd tools/ && ./bootstrap
    - name: Check all .cc , .h, .proto files for correct code format
      run: chmod +x tools/check_style.sh && tools/./check_style.sh

