name: Check Code Style

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main" 

jobs:
  check_code_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Initialize and update submodule
        run: git submodule update --init --recursive

      # Call the composite action to check files
      # for correct code style. This action (action.yml)
      # is in `3rdparty/dev-tools/check-code-style` submodule's
      # directory.
      - uses: 3rdparty/dev-tools/check-code-style@main
