name: clang-tidy-review

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # There is no clang-tidy preinstalled on ubuntu.
    # So we need to install it.
    - name: Install clang-tidy
      run: | 
        sudo apt-get install -y clang-tidy-12
        sudo ln -s $(which clang-tidy-12) /usr/bin/clang-tidy
      
    - name: Run clang-tidy checks 
      run: bazel build //... --config clang-tidy
