# The workflow calls another workflow
# See docs:
# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Submodules Sync

on:
  # Run this workflow every 15 minutes.
  schedule:
    - cron: "0/15 * * * *"
  # Allows you to run this workflow manually from the Actions tab or through
  # the HTTP API.
  workflow_dispatch:

jobs:
  submodule-sync:
    uses: 3rdparty/dev-tools/.github/workflows/submodules-sync.yml@main
    with:
      scripts_directory: submodules/dev-tools/.github/workflows/scripts
    secrets:
      private_repo_access_as_rebot_token: ${{ secrets.PRIVATE_REPO_ACCESS_AS_REBOT_TOKEN }}
