# Workflow for Ubuntu (latest).
name: Ubuntu

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v1

      - name: Check for bazel
        run: bazel --version

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "12.0"  

      - name: Build
        run: bazel build --spawn_strategy=local --copt="-g" --strip="never" :eventuals

      - name: Debug Build using tmate (if failure)
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

      - name: Test
        run: bazel test --spawn_strategy=local --copt="-g" --strip="never" --test_output=errors test:eventuals --test_arg=--gtest_shuffle --test_arg=--gtest_repeat=100

      - name: Debug Test using tmate (in failure)
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
