# Workflow for Windows (latest).
name: Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: windows-latest

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v1

      - name: Check for bazel
        run: bazel --version

      - name: pip install wheel
        run: pip install wheel

      - name: Build
        run: bazel build --spawn_strategy=local --strip="never" :grpc

      - name: Debug Build using tmate (if failure)
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

      - name: Test
        run: bazel test --spawn_strategy=local --strip="never" --test_output=errors test:grpc --test_arg=--gtest_shuffle --test_arg=--gtest_repeat=100

      - name: Debug Test using tmate (if failure)
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
