# Workflow for Windows (latest).
name: Windows

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "master"

jobs:
  build-and-test:
    name: Build and Test
    runs-on: windows-latest
    # We want to run on external PRs, but not on our own internal PRs as
    # they'll be run by the push to the branch
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != '3rdparty/stout-grpc'

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Check for bazel
        run: bazel --version

      - name: pip install wheel
        run: pip install wheel

      - name: Build
        run: bazel build --spawn_strategy=local --strip="never" :grpc

      - name: Debug Build using tmate (if failure)
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

      - name: Test
        run: bazel test --spawn_strategy=local --strip="never" --test_output=errors test:grpc --test_arg=--gtest_shuffle --test_arg=--gtest_repeat=100

      - name: Debug Test using tmate (if failure)
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
